### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by hrebchuk-oleh** [austinoboyle/scrape-linkedin-selenium#11]
>>> from scrape_linkedin import ProfileScraper

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/scrape_linkedin/__init__.py", line 4, in <module>
    from .ParallelScraper import scrape_in_parallel
  File "/usr/local/lib/python2.7/dist-packages/scrape_linkedin/ParallelScraper.py", line 37
    all_data = {**all_data, **json.load(data)}

**Comment by austinoboyle** [comment]
Oops, that is a python3 only syntax.  I will update so it works with Python2 as well
