### ISSUE TITLE
'Scraper' object has no attribute 'get_profile'

### ISSUE THREAD

**Issue by arnakoguzhan** [austinoboyle/scrape-linkedin-selenium#23]
I got this error when I try to run 

`
scrapeli --user=oguzhanarnak -o test.json
`

```
Traceback (most recent call last):
  File "/Users/oz/anaconda3/bin/scrapeli", line 11, in <module>
    load_entry_point('scrape-linkedin==0.1.1', 'console_scripts', 'scrapeli')()
  File "/Users/oz/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/oz/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/oz/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/oz/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/oz/anaconda3/lib/python3.6/site-packages/scrape_linkedin-0.1.1-py3.6.egg/scrape_linkedin/cli.py", line 39, in scrape
    profile = scraper.get_profile(url)
AttributeError: 'Scraper' object has no attribute 'get_profile'

```

Can you help me to fix this
Thanks.

**Comment by austinoboyle** [comment]
It looks like you have an old version of the CLI with a newer version of the package code.  Could you try upgrading the latest version with `pip install --upgrade git+git://github.com/austinoboyle/scrape-linkedin-selenium.git`?

**Comment by austinoboyle** [comment]
Have you tried this? Any update?
