### ISSUE TITLE
Already set LI_AT in cmd,but when run scraper still got error

### ISSUE THREAD

**Issue by Cinmay2014** [austinoboyle/scrape-linkedin-selenium#34]
Hi Austin,
Need help.
I tried to set LI_AT in win10, and I can see LI_AT value when I key in set in cmd. But when I tried to use scraper, Istill got error:
Traceback (most recent call last):
File "C:/Users/xxx/PycharmProjects/linkedin/test.py", line 6, in 
with CompanyScraper(cookie='xxxxxxxxx') as scraper:
File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\scrape_linkedin-0.5.1-py3.6.egg\scrape_linkedin\Scraper.py", line 52, in init
cookie = environ['LI_AT']
File "C:\Users\xxxx\AppData\Local\Programs\Python\Python36\lib\os.py", line 669, in getitem
raise KeyError(key) from None
KeyError: 'LI_AT'

**Comment by austinoboyle** [comment]
Fixed, was a bug in the Scraper code.  Thanks.  Now this DOES mean that if you had used 'set' or 'setx' to set the environment variable, it wasn't working properly, as Python could not find LI_AT in the environment.  The fix should allow you to pass cookie='xxxxx' in and work as expected now though.
