### ISSUE TITLE
selenium.common.exceptions.TimeoutException: Message:

### ISSUE THREAD

**Issue by rambabumuddasani** [austinoboyle/scrape-linkedin-selenium#46]
Hi 

I am getting the fallowing error during the profile info call.

scrapeli --user=austinoboyle

Traceback (most recent call last):
  File "C:\Users\welcome\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scrape_linkedin-0.5.4-py3.7.egg\scrape_linkedin\ProfileScraper.py", line 49, in load_profile_page
    (By.CSS_SELECTOR, '.profile-unavailable'))
  File "C:\Users\welcome\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\welcome\AppData\Local\Programs\Python\Python37-32\Scripts\scrapeli-script.py", line 11, in <module>
    load_entry_point('scrape-linkedin==0.5.4', 'console_scripts', 'scrapeli')()
  File "C:\Users\welcome\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\welcome\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\welcome\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\welcome\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\welcome\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scrape_linkedin-0.5.4-py3.7.egg\scrape_linkedin\cli.py", line 58, in scrape
    profile = scraper.scrape(url=url)
  File "C:\Users\welcome\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scrape_linkedin-0.5.4-py3.7.egg\scrape_linkedin\ProfileScraper.py", line 26, in scrape
    self.load_profile_page(url, user)
  File "C:\Users\welcome\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scrape_linkedin-0.5.4-py3.7.egg\scrape_linkedin\ProfileScraper.py", line 59, in load_profile_page
    """)
ValueError: Took too long to load profile.  Common problems/solutions:
                1. Invalid LI_AT value: ensure that yours is correct (they
                   update frequently)
                2. Slow Internet: increase the time out parameter in the Scraper
                   constructor
                3. Invalid e-mail address (or user does not allow e-mail scrapes) on scrape_by_email call

I have setup LI_AT cookie, in browser, i am able to see the requested profile data, but after sometime, browser is closing and in console i am seeing the above exception. I increased the timeout, still i am seeing the above error. 

Please help to fix.

Thank you in advance.

Regards,
Ram

**Comment by rambabumuddasani** [comment]
Issue fixed, when i ran this application with Administrative permissions in my windows operation system.
