### ISSUE TITLE
ImportError: cannot import name '_find_element'

### ISSUE THREAD

**Issue by chankeypathak** [austinoboyle/scrape-linkedin-selenium#72]
I cloned the repo and installed dependencies by `python setup.py install` but something seems to be broken.

```
E:\Users\chank>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from scrape_linkedin import CompanyScraper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Users\chank\AppData\Local\Programs\Python\Python37\lib\site-packages\scrape_linkedin-0.6.2-py3.7.egg\scrape_linkedin\__init__.py", line 1, in <module>
    from .utils import *
  File "E:\Users\chank\AppData\Local\Programs\Python\Python37\lib\site-packages\scrape_linkedin-0.6.2-py3.7.egg\scrape_linkedin\utils.py", line 2, in <module>
    from selenium.webdriver.support.expected_conditions import _find_element
ImportError: cannot import name '_find_element' from 'selenium.webdriver.support.expected_conditions' (E:\Users\chank\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium-4.0.0a6.post2-py3.7.egg\selenium\webdriver\support\expected_conditions.py)
>>>

```

**Comment by Lunfer** [comment]
I have this issue as well...

**Comment by Kaan191** [comment]
Check your Selenium version. The leading underscore in _find_element means it's a private function which means it has a greater chance of being subject to change.

On 3 Jun 2021, at 14:02, Lunfer ***@***.***> wrote:

﻿
I have this issue as well...
