### ISSUE TITLE
Companyscraper doesn't work and returns error 'NoneType'

### ISSUE THREAD

**Issue by RaniMounikaKotakadi** [austinoboyle/scrape-linkedin-selenium#78]
unable to get the company website
Company Attrs: ['overview', 'jobs', 'life', 'insights']
Error!!!
Traceback (most recent call last):
  File "linkedin_scrapper_chrome.py", line 72, in <module>
    company_overview_dict = company.to_dict()
  File "/xxx/xxxx/linkedin_scrapper/scrape_linkedin/ResultsObject.py", line 13, in to_dict
    return dict(zip(self.attributes, vals))
  File "/xxxx/xxxx/linkedin_scrapper/scrape_linkedin/ResultsObject.py", line 12, in <lambda>
    vals = map(lambda attr: getattr(self, attr), self.attributes)
  File "/xxxx/xxxxx/linkedin_scrapper/scrape_linkedin/Company.py", line 34, in overview
    overview['description'] = container.select_one(
AttributeError: 'NoneType' object has no attribute 'select_one'

**Comment by RaniMounikaKotakadi** [comment]
Hi @austinoboyle,

Found that there is no .error-container selector available on [companyscrapper.py](https://github.com/austinoboyle/scrape-linkedin-selenium/blob/master/scrape_linkedin/CompanyScraper.py)

load_initial() function
```
EC.presence_of_element_located
                    (By.CSS_SELECTOR, '.error-container'))
```

Also, from get_overview function, the following attribute is unavailable from the UI

```
tab_link = self.driver.find_element_by_css_selector(
                'a[data-control-name="page_member_main_nav_about_tab"]')
```

**Comment by ehsong** [comment]
Hi, I have the same issue -- I get the message:

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/eunhousong/anaconda3/lib/python3.7/site-packages/scrape_linkedin/ResultsObject.py", line 13, in to_dict
    return dict(zip(self.attributes, vals))
  File "/Users/eunhousong/anaconda3/lib/python3.7/site-packages/scrape_linkedin/ResultsObject.py", line 12, in <lambda>
    vals = map(lambda attr: getattr(self, attr), self.attributes)
  File "/Users/eunhousong/anaconda3/lib/python3.7/site-packages/scrape_linkedin/Company.py", line 34, in overview
    overview['description'] = container.select_one(
AttributeError: 'NoneType' object has no attribute 'select_one'
```

**Comment by austinoboyle** [comment]
Yes, this is due to a change in the LinkedIn UI. This happens once fairly frequently, and it's difficult to keep up. If you have a fix for the issue, I would be happy to approve a pull request.

**Comment by RohitRana19** [comment]
Hello Sir I would like to contribute to this issue

**Comment by Roy6801** [comment]
Hello Sir, I've left a pull request for this issue, please look into it.
