### ISSUE TITLE
No such file or directory: 'chromedriver': 'chromedriver' / Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

### ISSUE THREAD

**Issue by ffs-sp** [austinoboyle/scrape-linkedin-selenium#83]
I ran the example and got the following error:

/Users/Francesco/PycharmProjects/LinkedIn/venv/bin/python /Users/Francesco/PycharmProjects/LinkedIn/main.py
Traceback (most recent call last):
  File "/Users/Francesco/PycharmProjects/LinkedIn/venv/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Francesco/PycharmProjects/LinkedIn/main.py", line 9, in <module>
    with CompanyScraper() as scraper:
  File "/Users/Francesco/PycharmProjects/LinkedIn/venv/lib/python3.7/site-packages/scrape_linkedin/Scraper.py", line 39, in __init__
    self.driver = driver(**driver_options)
  File "/Users/Francesco/PycharmProjects/LinkedIn/venv/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Users/Francesco/PycharmProjects/LinkedIn/venv/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by austinoboyle** [comment]
The chromedriver executable needs to be downloaded and in your system's PATH. You can download the executable at the link in the error message. Instructions for editing your PATH (I see you're using a MAC) are here: https://stackoverflow.com/questions/7703041/editing-path-variable-on-mac
